### ISSUE TITLE
Task was destroyed but still pending

### ISSUE THREAD

**Issue by Cadair** [Cadair/parfive#46]
```
Task was destroyed but it is pending!
task: <Task pending name='Task-119' coro=<Downloader._write_worker() running at /home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/4315/lib/python3.8/site-packages/parfive/downloader.py:469> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7fdd519a08e0>()]>>
Exception ignored in: <coroutine object Downloader._write_worker at 0x7fdd51988440>
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/4315/lib/python3.8/site-packages/parfive/downloader.py", line 469, in _write_worker
    offset, chunk = await queue.get()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/4315/lib/python3.8/asyncio/queues.py", line 165, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/4315/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/home/docs/checkouts/readthedocs.org/user_builds/sunpy/conda/4315/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by lzivadinovic** [comment]
Can confirm. I have problem with this issue a lot.

**Comment by Cadair** [comment]
You got anything which can reliably reproduce it? I have found it very hard to debug.

**Comment by lzivadinovic** [comment]
Hi, not really. I _think_ its related with downloading big files and timeout errors (because those come in pair with this error most of the time). I've been using modified sunpy library (https://github.com/sunpy/sunpy/pull/4405) to download tar files instead of fits, and it started occurring. If i manage to reproduce it, i will ping you.

**Comment by Cadair** [comment]
Chatting to @dstansby leads me to wonder if as either a cause or side effect of this we are leaving connections open when we shouldn't be. He saw that on multiple calls to `.download()` in sequence he was getting connection refused errors, which could be because a max was hit against the server.

**Comment by Cadair** [comment]
This doesn't seem to just be related to retry. It also seems to be happening with just a call to `download`.

Last time I saw this in the sunpy doc build I got the following:
```
DEBUG: Failed to download EVE_TIMESERIES from https://github.com/sunpy/sample-data/raw/master/sunpy/v1/20110607_EVE_L0CS_DIODES_1m.txt: 400, message='Can not decode content-encoding: gzip' [sunpy.data._sample]
DEBUG: Attempting redownload of EVE_TIMESERIES using http://data.sunpy.org/sunpy/v1/20110607_EVE_L0CS_DIODES_1m.txt [sunpy.data._sample]
Task was destroyed but it is pending!
task: <Task pending name='Task-411' coro=<Downloader._write_worker() running at /home/stuart/Git/sunpy/.tox/build_docs/lib/python3.8/site-packages/parfive/downloader.py:469> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f6a080f6520>()]>>
Exception ignored in: <coroutine object Downloader._write_worker at 0x7f6a08271b40>
Traceback (most recent call last):
  File "/home/stuart/Git/sunpy/.tox/build_docs/lib/python3.8/site-packages/parfive/downloader.py", line 469, in _write_worker
    offset, chunk = await queue.get()
  File "/usr/lib/python3.8/asyncio/queues.py", line 165, in get
    getter.cancel()  # Just in case getter is not done yet.
  File "/usr/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
...
/usr/lib/python3.8/asyncio/selector_events.py:694: ResourceWarning: unclosed transport <_SelectorSocketTransport fd=14 read=idle write=<idle, bufsize=0>>                                                                                                      
  _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)

/usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>                                                                                                            
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
```

**Comment by Cadair** [comment]
I am going to be interested in how #53 affects this error.

**Comment by nabobalis** [comment]
I've not seen this on RTD at least.

**Comment by Cadair** [comment]
Based on various feedback I am going to close this.
